-- ================================================== USER DEFINED FUNCTIONS =========================================================

-- ================================================== SCALAR VALUED FUNCTION ==========================================================

-- THE USER DEINED FUNCTION WHICH RETURNS ONLY A SINGLE VALUE(SCALAR VALUE) IS KNOWN AS SCALAR VALUED FUNCTIONS.

-- THE RETURNED VALUE CAN BE OF ANY DATATYPE, EXCEPT TEXT, NTEXT, IMAGE, CURSOR AND TIMESTAMP.

-- SCALAR FUNCTIONS ACCEPT ONE OR MORE PARAMETERS BUT RETURN ONLY ONE VALUE THEREFORE THEY MUST INCLUDE A RETURN STATEMENT.

-- WE CAN USE IF BLOCKS AND WHILE LOOP LOGIC IN SCALAR FUNCTION.

-- SCALAR FUNCTION CANNOT UPDATE DATA.

CREATE FUNCTION NOCUBE(@X INT)
RETURNS INT
AS
BEGIN
RETURN  @X * @X * @X;
END

-- EXECUTE FUNCTION

SELECT DBO.NOCUBE(4);

-- CALCULATE THE AGE.

CREATE FUNCTION CALCULATEAGE
(
 @DOB DATE
)
RETURNS INT
AS
BEGIN
DECLARE @AGE INT
SET @AGE = DATEDIFF(YEAR, @DOB, GETDATE()) -
CASE 
   WHEN (MONTH(@DOB) > MONTH(GETDATE())) OR
        (MONTH(@DOB) = MONTH(GETDATE()) AND
		DAY(@DOB) > DAY(GETDATE()))
		THEN 1
		 ELSE 0
	END 
	RETURN @AGE
END

-- EXECUTE THE FUNCTION.

SELECT DBO.CALCULATEAGE('12/29/1988');

-- CREATE A SCALAR FUNCTION WITHOUT PARAMETER.

CREATE FUNCTION SHOWMESSAGE()
RETURNS VARCHAR(100)
AS
BEGIN
 RETURN 'WELCOME TO SQL SERVER'
END

SELECT DBO.SHOWMESSAGE();

SELECT SHOWMESSAGE();  -- IT WILL SHOW ERROR ''SHOWMESSAGE' is not a recognized built-in function name.'

-- CREATE A SCALAR FUNCTION WITH SINGLE PARAMETER.

CREATE FUNCTION TAKEANUMBER(@NUM INT)
RETURNS INT
AS
BEGIN
 RETURN (@NUM * @NUM)
END

SELECT DBO.TAKEANUMBER(5);

-- ALTER A SCALAR FUNCTION.

ALTER FUNCTION MULTIPLENUMBER(@NUM INT)
RETURNS INT
AS
BEGIN
 RETURN (@NUM * @NUM * @NUM)
END

SELECT DBO.MULTIPLENUMBER(7);

--DROP A FUNCTION.

DROP FUNCTION DBO.MULTIPLENUMBER();

-- IF BLOCK IN SCALAR FUNCTION.

CREATE FUNCTION VOTERAGE(@AGE INT)
RETURNS VARCHAR(MAX)
AS  
BEGIN 
 DECLARE @STR VARCHAR(MAX)
 IF @AGE >= 18
 BEGIN
 SET @STR = 'YOU ARE ELIGIBLE TO VOTE.';
 END

 ELSE
 BEGIN
 SET @STR = 'YOU ARE NOT ELIGIBLE TO VOTE.';
 END
 RETURN @STR
END

SELECT VOTERAGE(20);

-- SCALAR FUNCTION CAN CALL ANOTHER FUNCTION.

CREATE FUNCTION DATES()
RETURNS DATE
AS
BEGIN
 RETURN GETDATE()
END

SELECT DBO.DATES();

-- ================================================ INLINE TABLE VALUED FUNCTION ==========================================================

-- CONTAINS A SINGLE T-SQL STATEMENT AND RETURNS A TABLE SET.

-- IT RETURNS A TABLE.

-- WE HAVE TO SPECIFY TABLE AS RETURN TYPE,INSTEAD OF ANY SCALAR DATATYPE LIKE INT, VARCHAR ETC.

-- THERE IS NO BEGIN AND END BLOCKS.

CREATE FUNCTION FN_GETSTUDENTS()
RETURNS TABLE
AS
RETURN (SELECT * FROM STUDENTS1);

SELECT * FROM FN_GETSTUDENTS();

CREATE FUNCTION FN_GETSTUDENTWITHAGE(@AGE INT)
RETURNS TABLE 
AS
RETURN (SELECT * FROM STUDENTS1 WHERE AGE = @AGE)

SELECT * FROM FN_GETSTUDENTWITHAGE(22);

-- JOIN WITH INLINE TABLE VALUED FUNCTION.

SELECT * FROM FN_GETSTUDENTWITHAGE(22) AS A 
INNER JOIN STU_DEPT B
ON A.USN = B.USN; 

SELECT * FROM STU_DEPT;









