-- TRANSACTION CONTROL LANGUAGE (TCL)

SELECT * FROM PRODUCTION.PRODUCT;

-- CREATE A DUPLICATE TABLE,

SELECT * INTO PRODUCTDUP FROM PRODUCTION.PRODUCT;

SELECT * FROM PRODUCTDUP;

-- COMMIT

BEGIN TRANSACTION
UPDATE PRODUCTDUP
SET  SAFETYSTOCKLEVEL = 2000
WHERE REORDERPOINT = 750;

COMMIT;

--ROLLBACK

BEGIN TRANSACTION
UPDATE PRODUCTDUP
SET  SAFETYSTOCKLEVEL = 2000
WHERE REORDERPOINT = 750;

ROLLBACK;

SELECT * FROM PRODUCTDUP;