-- ================================ SET OPERATOR IN SQL ======================================================

CREATE TABLE COURSE_B(
COURSEID INT,
COURSENAME VARCHAR(30)
);

INSERT INTO COURSE_B VALUES(1,'ARTS');
INSERT INTO COURSE_B VALUES(2,'SCIENCE');
INSERT INTO COURSE_B VALUES(3,'COMMERCE');
INSERT INTO COURSE_B VALUES(4,'IT');
INSERT INTO COURSE_B VALUES(7,'DATA SCIENCE');

SELECT * FROM COURSE_B;

CREATE TABLE COURSE_A
(
COURSEID INT,
COURSENAME VARCHAR(30)
);

INSERT INTO COURSE_A VALUES(1,'ARTS');
INSERT INTO COURSE_A VALUES(2,'SCIENCE');
INSERT INTO COURSE_A VALUES(3,'COMMERCE');
INSERT INTO COURSE_A VALUES(4,'IT');
INSERT INTO COURSE_A VALUES(9,'DATA ANALYST');
INSERT INTO COURSE_A(COURSEID) VALUES(10);

SELECT * FROM COURSE_A;
SELECT * FROM COURSE_B;

-- UNION : REMOVING THE DUPLICATE VALUES.

SELECT COURSEID,COURSENAME FROM COURSE_A
UNION
SELECT COURSEID,COURSENAME FROM COURSE_B;

-- UNION ALL : NOT REMOVING THE DUPLICATE VALUES.

SELECT COURSEID,COURSENAME FROM COURSE_A
UNION ALL
SELECT COURSEID,COURSENAME FROM COURSE_B;

-- DATATYPES OF BOTH TABLES SHOULD BE MATCH FROM ONE ANOTHER OTHERWISE IT WILL THROW AN ERROR.

SELECT COURSEID,COURSENAME FROM COURSE_A
UNION ALL                           -- iT WILL SHOW Conversion failed when converting the varchar value 'ARTS' to data type int.
SELECT COURSENAME,COURSEID FROM COURSE_B;

-- NUMBER OF COLUMNS MUST BE SAME IN BOTH TABLES.

SELECT COURSEID,COURSENAME FROM COURSE_A    
UNION -- All queries combined using a UNION, INTERSECT or EXCEPT operator must have an equal number of expressions in their target lists.
SELECT COURSEID FROM COURSE_B;

SELECT COURSEID,COURSENAME FROM COURSE_A
UNION ALL
SELECT COURSEID,NULL AS 'CFEE' FROM COURSE_B;

SELECT COURSEID,COURSENAME FROM COURSE_A
UNION 
SELECT COURSEID,NULL AS 'CFEE' FROM COURSE_B;

-- INTERSECT : EQUIVALENT TO INNER JOIN.

SELECT COURSEID,COURSENAME FROM COURSE_A
INTERSECT
SELECT COURSEID,COURSENAME FROM COURSE_B;

-- EXCEPT

SELECT COURSEID,COURSENAME FROM COURSE_A
EXCEPT
SELECT COURSEID,COURSENAME FROM COURSE_B;