-- DIFFERENCE BETWEEN DATETIME AND DATETIME2.

DECLARE @DATETIME DATETIME, @DATETIME2 DATETIME2

SET @DATETIME = GETUTCDATE()
SET @DATETIME2 = GETUTCDATE()

SELECT @DATETIME;
SELECT @DATETIME2;

-- DATETIME AND DATETIME2 BOTH PROVIDE DATA IN DATE AND TIME INCLUDING MILISECONDS.
--BUT DATETIME2 PROVIDE MORE ACCURATE DATETIME IN MILISECONDS AS COMPARE TO DATETIME.