-- ======================================== USER DEFINED FUNCTIONS ==============================================

-- ======================================== SCALAR FUNCTION IN SQL ==============================================

SELECT * FROM SALESLT.CUSTOMER;

-- CREATING FUNCTION TO GET CUSTOMER FULL NAME

CREATE FUNCTION FUN_FULLNAME
(
 @FIRSTNAME VARCHAR(50),
 @LASTNAME VARCHAR(50)
)
RETURNS VARCHAR(101)
AS
BEGIN
RETURN(SELECT @FIRSTNAME+' '+@LASTNAME)
END

-- CALLING THE FUNCTION

SELECT DBO.FUN_FULLNAME(FIRSTNAME,LASTNAME) AS FULLNAME,* FROM SALESLT.CUSTOMER;

-- CREATING FUNCTION TO GET USERNAME FROM EMAIL.

CREATE FUNCTION FUN_GETUSERNAME
(
 @USERNAME VARCHAR(50)
)
RETURNS VARCHAR(50)
AS
BEGIN
RETURN (SELECT SUBSTRING(@USERNAME,1,CHARINDEX('@',@USERNAME)-1)) 
END

-- CALLING THE FUNCTION

SELECT DBO.FUN_GETUSERNAME(EMAILADDRESS) AS USERNAME,* FROM SALESLT.CUSTOMER;

-- CREATING A FUNCTION TO GET FIRST 3 CHARACTER FROM FIRSTNAME.

CREATE FUNCTION FUN_FIRSTTHREELETTER
(
 @NAME VARCHAR(10)
)
RETURNS VARCHAR(10)
AS
BEGIN
RETURN(SELECT LEFT(@NAME,3))
END

-- CALLING THE FUNCTION.

SELECT DBO.FUN_FIRSTTHREELETTER(FIRSTNAME) AS FIRSTNAME,* FROM SALESLT.CUSTOMER;

-- CREATING A FUNCTION TO GET FIRST 4 CHARACTER FROM FIRSTNAME.

CREATE FUNCTION FUN_FIRSTFOURLETTER
(
 @NAME VARCHAR(10)
)
RETURNS VARCHAR(10)
AS
BEGIN
RETURN(SELECT LEFT(@NAME,4))
END

-- CALLING THE FUNCTION.

SELECT DBO.FUN_FIRSTFOURLETTER(FIRSTNAME) AS FIRSTNAME,* FROM SALESLT.CUSTOMER;

SELECT * FROM EMPLOYEES;

-- CREATE A FUNCTION TO FIND THE AGE OF EMPLOYEE WHERE INPUT PARAMETER IS EMPLOYEE ID.




-- ======================================== INLINE TABLE VALUED FUNCTION IN SQL ==============================================

SELECT * FROM SALESLT.ADDRESS;

SELECT * FROM SALESLT.CUSTOMER;

SELECT * FROM SALESLT.CUSTOMERADDRESS;

SELECT * FROM SALESLT.PRODUCT;

SELECT * FROM SALESLT.PRODUCTCATEGORY;

SELECT * FROM SALESLT.PRODUCTDESCRIPTION;

SELECT * FROM SALESLT.PRODUCTMODEL;

SELECT * FROM SALESLT.SALESORDERDETAIL;

SELECT * FROM SALESLT.SALESORDERHEADER;














