-- TEMPORARY TABLE

-- LOCAL TEMPORARY TABLE

CREATE TABLE #EMPLOYEE(
EID INT IDENTITY(1,1),
ENAME VARCHAR(30),
ESAL INT);

INSERT INTO #EMPLOYEE VALUES('GAURAV',55000);
INSERT INTO #EMPLOYEE VALUES('AMAN',15000);
INSERT INTO #EMPLOYEE VALUES('RAJESH',60000);
INSERT INTO #EMPLOYEE VALUES('NISHA',10000);
INSERT INTO #EMPLOYEE VALUES('SONU',30000);

SELECT * FROM #EMPLOYEE;

-- GLOBAL TEMPORARY TABLE

CREATE TABLE ##EMPLOYEE(
EID INT IDENTITY(1,1),
ENAME VARCHAR(30),
ESAL INT);

INSERT INTO ##EMPLOYEE VALUES('GAURAV',55000);
INSERT INTO ##EMPLOYEE VALUES('AMAN',15000);
INSERT INTO ##EMPLOYEE VALUES('RAJESH',60000);
INSERT INTO ##EMPLOYEE VALUES('NISHA',10000);
INSERT INTO ##EMPLOYEE VALUES('SONU',30000);

SELECT * FROM ##EMPLOYEE;

--TABLE VARIABLE

DECLARE @EMP TABLE(EID INT, ENAME VARCHAR(50));

INSERT INTO @EMP VALUES(1,'GAURAV');

INSERT INTO @EMP VALUES(2,'AMAN');

SELECT * FROM @EMP;
