-- IDENTITY OPERATOR

CREATE TABLE STUDENT(
ID INT IDENTITY(1,1),
SNAME VARCHAR(30),
SAGE INT);

INSERT INTO STUDENT VALUES('RAM',20);
INSERT INTO STUDENT VALUES('SHYAM',15);
INSERT INTO STUDENT VALUES('OM',10);

DROP TABLE STUDENT;

SELECT * FROM STUDENT;

--MANUALLY INSERT RECORD IN IDENTITY COLUMN.

INSERT INTO STUDENT VALUES(4,'AMAN',25); 

INSERT INTO STUDENT VALUES(5,'GAURAV',29); 

/* IT WILL SHOW ERROR "An explicit value for the identity column in table 'STUDENT' can only be specified when a 
column list is used and IDENTITY_INSERT is ON. " */

-- TO MANUALLY INSERT A NEW VALUE INTO THE ID COLUMN, WE FIRST MUST SET THE IDENTITY_INSERT FLAG ON.

-- TURN IDENTITY_INSERT ON.

SET IDENTITY_INSERT STUDENT ON;

INSERT INTO STUDENT(ID,SNAME,SAGE) VALUES(5,'GAURAV',29); 

SELECT * FROM STUDENT;

-- TURN IDENTITY_INSERT OFF.

SET IDENTITY_INSERT STUDENT OFF;

INSERT INTO STUDENT(ID,SNAME,SAGE) VALUES(7,'AMAN',25); -- NOW IT AGAIN SHOW ERROR.

-- HOW TO RESET IDENTITY COLUMN VALUE.

DBCC CHECKIDENT ('STUDENT');

DBCC CHECKIDENT('STUDENT',RESEED, 30);

INSERT INTO STUDENT VALUES('GAURAV',29); 

INSERT INTO STUDENT VALUES('AMAN',25); 

SELECT * FROM STUDENT;

-- BUT WE CAN'T INSERT DATA MANUALLY IN IDENTITY COLUMN NOW.

INSERT INTO STUDENT(ID,SNAME,SAGE) VALUES(37,'NISHA',25); --THROW AN ERROR.


