--DECIMAL DATA TYPE

DECLARE @A DECIMAL(20,3)
SET @A = 2345672.678954
PRINT @A;

DECLARE @B DECIMAL(38,2)
SET  @B = 1100.3968857
PRINT @B;

--FLOAT DATA TYPE

DECLARE @C FLOAT
SET @C = 10.56789
PRINT @C;

--CHAR DATA TYPE

-- CHAR IS A FIXED LENGTH STRING DATATYPE, SO ANY REMAINING SPACE IN THE FIELD IS PADDED WITH BLANKS.
-- CHAR TAKES A 1 BYTE PER CHARACTER, SO A CHAR(100) FIELD TAKES UP 100 BYTES ON DISK.

DECLARE @D CHAR(20)
SET @D = 'AMAN@897'
PRINT @D;

--VARCHAR DATA TYPE

-- VARCHAR IS A VARIABLE LENGTH STRING DATATYPE, SO IT HOLDS ONY THE CHARACTER WE ASSIN TO IT.
-- CHAR TAKES A 1 BYTE PER CHARACTER, + 2 BYTES TO HOLD LENGTH INFORMATION.
-- FOR EXAMPLE WE SET VARCHAR(100) DATA TYPE = 'AMAN'
-- THEN IT WOULD TAKE UP 4 BYTES ('A','M','A','N') + 2 BYTES = 9 BYTES FOR ALL.

DECLARE @E VARCHAR(30)
SET @E = 'GAURAV SINGH DHAKRE'
PRINT @E;

-- NVARCHAR DATA TYPE

DECLARE @F NVARCHAR(4)
SET @F = 'GAURAV'
PRINT @F;   -- RETURN 'GAUR' AND TRUNCATE OTHER CHARACTER.

DECLARE @G NVARCHAR(MAX)
SET @G = 'GAURAV SINGH DHAKRE'
PRINT @G;