-- ============================= WHILE LOOP ==========================================

-- HOW WE CAN PRINT A-Z.

SELECT ASCII('K');

SELECT CHAR(73);

DECLARE  @A INT, @B INT

SET @A = 65
SET @B = 90

WHILE @A <= @B
BEGIN
   PRINT CHAR(@A)
   SET @A = @A+1;
END

-- HOW WE CAN PRINT a-z.

DECLARE @C INT, @D INT

SET @C = 97
SET @D = 122

WHILE @C <= @D
BEGIN
  PRINT CHAR(@C)
  SET @C = @C+1;
END;

SELECT * FROM SALESLT.CUSTOMER;

SELECT * FROM CUSTOMER_DUP;

ALTER TABLE  CUSTOMER_DUP ADD GENDER VARCHAR(10);

/* UPDATE DBO.CUSTOMER_DUP 
SET GENDER = 'M' WHERE TITLE = 'Mr.'
AND GENDER = 'F' WHERE TITLE = 'Ms.'; */


SELECT * FROM CUSTOMER_DUP WHERE CUSTOMERID IN (SELECT MIN(CUSTOMERID) FROM CUSTOMER_DUP);

SELECT * FROM CUSTOMER_DUP WHERE CUSTOMERID = (SELECT MAX(CUSTOMERID) FROM CUSTOMER_DUP);

DECLARE @MAX INT, @MIN INT, @EMAILADDRESS NVARCHAR(500), @TITLE VARCHAR(100)

SELECT @MAX = MAX(CUSTOMERID), @MIN= MIN(CUSTOMERID) FROM CUSTOMER_DUP;

WHILE @MIN <= @MAX
BEGIN
SELECT @EMAILADDRESS = EMAILADDRESS, @TITLE=TITLE FROM CUSTOMER_DUP WHERE CUSTOMERID = @MIN;

IF @TITLE = 'Mr.'
BEGIN 
UPDATE CUSTOMER_DUP
SET SUFFIX = LEFT(EMAILADDRESS,3)
WHERE CUSTOMERID = @MIN
END

IF @TITLE = 'Ms.'
BEGIN
UPDATE CUSTOMER_DUP
SET SUFFIX = LEFT(EMAILADDRESS,4)
WHERE CUSTOMERID = @MIN
END

SET @MIN = @MIN+1;
END

SELECT * FROM CUSTOMER_DUP;


