-- DATETIME FUNCTION

-- GETDATE()

SELECT GETDATE();

SELECT *,GETDATE() AS RESULTDATE FROM EMPLOYEES;

-- DATEADD()

SELECT DATEADD(DAY,90,GETDATE());

SELECT DATEADD(DAY,-250,GETDATE());

-- DATEPART()

SELECT DATEPART(DAY, GETDATE());

SELECT DATEPART(MONTH, GETDATE());

SELECT DATEPART(YEAR, GETDATE());

SELECT * FROM SALESLT.PRODUCT;

SELECT DATEPART(YEAR,SELLSTARTDATE) AS SELLYEAR,SELLSTARTDATE,* FROM SALESLT.PRODUCT;

-- FIND THE PRODUCT INFORMATION WHICH SELLSTARTDATE YEAR IS 2002.

SELECT * FROM SALESLT.PRODUCT WHERE DATEPART(YEAR,SELLSTARTDATE) = '2002';

---- FIND THE PRODUCT INFORMATION WHICH SELLSTARTDATE MONTH IS O7(JULY).

SELECT * FROM SALESLT.PRODUCT WHERE DATEPART(MONTH,SELLSTARTDATE) = '07';

-- DATEDIFF()

SELECT * FROM HUMANRESOURCES.EMPLOYEE;

-- FIND THE AGE OF ALL EMPLOYEES.

SELECT DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE,BIRTHDATE, * FROM HUMANRESOURCES.EMPLOYEE;

--FIND THE EMPLOYEE DETAIL WHOSE AGE IS 55 YEAR.

SELECT DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE,* FROM HUMANRESOURCES.EMPLOYEE WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) = '55';

-- FIND THE DETAILS OF EMPLOYEE WHOSE EXPERIENCE IS GREATER THAN 10 YEARS.

SELECT DATEDIFF(YEAR,HIREDATE,GETDATE()) AS EXPERIENCE,* FROM HUMANRESOURCES.EMPLOYEE WHERE DATEDIFF(YEAR,HIREDATE,GETDATE()) >= 10;

-- DATENAME()

SELECT DATENAME(DW,GETDATE()) AS DAY;  -- " FRIDAY "

SELECT DATENAME(DW, '11/01/2024'); -- " FRIDAY ".

--FIND THE WEEKDAY OF EMPLOYEES FROM THEIR HIREDATE.

SELECT DATENAME(DW,HIREDATE) AS DAYS,* FROM HUMANRESOURCES.EMPLOYEE;

SELECT DATENAME(MONTH,GETDATE()) AS DATES;

-- EOMONTH()

SELECT EOMONTH(GETDATE()) AS 'LASTDAY';

SELECT EOMONTH('2024-02-15');

SELECT GETDATE() AS 'TODAY_DATE',
EOMONTH(GETDATE()) AS 'EOM DATE',
DATENAME(DW,GETDATE()) AS 'TODAY DAY',
DATENAME(DW, EOMONTH(GETDATE())) AS 'EOM DAY';

SELECT DATENAME(DW, EOMONTH('10/22/2024')) AS 'EOM DAY';



