-- ======================= DML QUERY IN VIEW ==============================

/* 
   * WE CAN USE SQL VIEWS TO INSERT, UPDATE AND DELETE DATA IN A SINGLE SQL TABLE.
   * IF A VIEW POINT A MULTIPLE TABLE THEN WE CAN'T PERFORM DML OPERATIONS.
   * WE CAN USE DML OPERATIONS ON A SINGLE TABLE ONLY.
   * VIEW SHOULD NOT CONTAIN GROUP BY, HAVING, DISTINCT CLAUSES.
   * WE CANNOT USE A SUBQUERY IN A VIEW IN SQL SERVER.

*/

SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES DROP COLUMN DEPARTMENT;

CREATE VIEW EMPLOYEE_VIEW9
AS
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEE_VIEW9;

DROP VIEW EMPLOYEES10;

CREATE TABLE EMPLOYEE_DETAILS(
EID INT IDENTITY(1,1) NOT NULL,
ENAME NVARCHAR(50) NOT NULL,
ECITY NVARCHAR(50) NOT NULL,
ESALARY INT NOT NULL);

INSERT INTO EMPLOYEE_DETAILS VALUES('RAM','AGRA',20000);
INSERT INTO EMPLOYEE_DETAILS VALUES('SHYAM','MATHURA',30000);
INSERT INTO EMPLOYEE_DETAILS VALUES('GAURAV','JAIPUR',15000);
INSERT INTO EMPLOYEE_DETAILS VALUES('AMAN','JAIPUR',10000);

SELECT * FROM EMPLOYEE_DETAILS;

CREATE VIEW EMPLOYEE_VIEW10
AS
SELECT EID,ENAME,ECITY FROM EMPLOYEE_DETAILS;

SELECT * FROM EMPLOYEE_VIEW10;

INSERT INTO EMPLOYEE_VIEW10 VALUES('GAGAN','NOIDA'); -- IT WILL THROW ERROR.

/* IF WE DEFINE ANY COLUMN WITH NOT NULL IN TABLE AND IF WE INSERT DATA INSIDE A VIEW WITHOUT USING THEM,
THEN DATA WILL NOT INSERTED INSIDE A VIEW. */

INSERT INTO EMPLOYEE_VIEW10 VALUES(6,'GAGAN','NOIDA',5000);

