-- CREATE A DATABASE

CREATE DATABASE PHONE;

-- SELECT A DATABASE

USE PHONE;

-- CREATE A TABLE

CREATE TABLE PHONES(ID INT, NAME VARCHAR(10));

-- SELECT A TABLE

SELECT * FROM PHONES;

-- ADD A COLUMN IN TABLE

ALTER TABLE PHONES ADD MODEL VARCHAR(30);

ALTER TABLE PHONES ADD COMPANY VARCHAR(30);

-- MODIFY A COLUMN IN TABLE

ALTER TABLE PHONES ALTER COLUMN NAME VARCHAR(50);

-- TO CHECK TABLE STRUCTURE

SP_HELP PHONES;

-- DROP A COLUMN FROM TABLE

ALTER TABLE PHONES DROP COLUMN COMPANY;

-- DROP A DATABASE

DROP DATABASE PHONE;

-- DROP A TABLE

DROP TABLE PHONES;

-- RENAME A DATABASE

SP_RENAMEDB 'PHONE','MPHONE'; 

-- RENAME A TABLE

SP_RENAME 'PHONES','MPHONES';

SELECT * FROM MPHONES;

--RENAME A COLUMN

SP_RENAME 'MPHONES.NAME','NAMES','COLUMN';

-- ADD A PRIMARY KEY CONSTRAINT

ALTER TABLE MPHONES ADD PRIMARY KEY (ID);

-- ADD A UNIQUE KEY CONSTRAINT

ALTER TABLE MPHONES ADD UNIQUE(NAMES);

-- ADD A CONSTRAINT TO COLUMN

ALTER TABLE MPHONES ALTER COLUMN ID INT NOT NULL;

SP_HELP MPHONES;
