-- ======================== STORED PROCEDURE ====================================

-- USER DEFINE STORED PROCEDURRE
-- 1) WITHOUT PARAMETER STORED PROCEDURE.
-- 2) WITH PARAMETER STORED PROCEDURE.

-- ============ -- 1) WITHOUT PARAMETER STORED PROCEDURE. ==================


SELECT * FROM EMPLOYEES;

SELECT * FROM EMP_DEPT;

-- CREATION OF WITHOUT PARAMETER STORED PROCEDURE.

CREATE PROCEDURE EMPPROC
AS
BEGIN
SELECT E1.EMP_ID,E1.NAME,E1.SALARY,E2.DEPT_ID,E2.DEPARTMENT
FROM EMPLOYEES E1
INNER JOIN EMP_DEPT E2
ON E1.EMP_ID = E2.EMP_ID;
END

---- EXECUTION OF WITHOUT PARAMETER STORED PROCEDURE.

EXEC EMPPROC;

-- TO SEE THE CODE/TEXT OF STORED PROCEDURE.

SP_HELPTEXT EMPPROC;

-- ============ -- 1) WITH PARAMETER STORED PROCEDURE. ==================

SELECT * FROM EMPLOYEES1;

SELECT * FROM EMP_DEPT1;

SELECT * FROM DEPARTMENT;

CREATE PROCEDURE EMPPROC1( @ENAME VARCHAR(100))
AS
BEGIN
SELECT E1.EMP_ID,E1.NAME,E1.SALARY,E2.DEPT_ID,E2.DEPARTMENT
FROM EMPLOYEES E1
INNER JOIN EMP_DEPT E2
ON E1.EMP_ID = E2.EMP_ID
WHERE E1.NAME = @ENAME;

SELECT  E1.EMP_ID,E1.EMP_FIRSTNAME,E2.DEPT_ID,E3.DEPT_NAME
FROM EMPLOYEES1 E1
JOIN EMP_DEPT E2
ON E1.EMP_ID = E2.EMP_ID
INNER JOIN DEPARTMENT E3 
ON E2.EMP_ID = E3.EMP_ID
WHERE E1.EMP_FIRSTNAME = @ENAME;
END

-- ALTER THE STORED PROCEDURE.

ALTER PROCEDURE EMPPROC1( @ENAME VARCHAR(100))
AS
BEGIN
SELECT E1.EMP_ID,E1.NAME,E1.SALARY,E2.DEPT_ID,E2.DEPARTMENT
FROM EMPLOYEES E1
INNER JOIN EMP_DEPT E2
ON E1.EMP_ID = E2.EMP_ID
WHERE E1.NAME = @ENAME;

SELECT  E1.EMP_ID,E1.EMP_FIRSTNAME,E2.DEPT_ID,E3.DEPT_NAME 
FROM EMPLOYEES1 E1
JOIN EMP_DEPT E2
ON E1.EMP_ID = E2.EMP_ID
INNER JOIN DEPARTMENT E3 
ON E2.EMP_ID = E3.EMP_ID
WHERE E1.EMP_FIRSTNAME = @ENAME;
END

EXEC EMPPROC1 'ROHAN';

-- OPTIONAL PARAMETER

CREATE PROCEDURE EMPPROC2( @EID INT = NULL)
AS
BEGIN
IF ISNULL(@EID,' ')=' '
BEGIN
SELECT E1.EMP_ID,E1.NAME,E1.SALARY,E2.DEPARTMENT 
FROM EMPLOYEES E1 JOIN EMP_DEPT E2
ON E1.EMP_ID = E2.EMP_ID;
END
ELSE
BEGIN
SELECT E1.EMP_ID,E1.NAME,E1.SALARY,E2.DEPARTMENT 
FROM EMPLOYEES E1 JOIN EMP_DEPT E2
ON E1.EMP_ID = E2.EMP_ID
WHERE E1.EMP_ID = @EID;
END
END

EXEC EMPPROC2 201;

EXEC EMPPROC2; -- IT WILL TAKE NULL BY DEFAULT.

EXEC EMPPROC2 @EID = NULL;

-- DATA VALIDATION IN STORED PROCEDURE.

-- HOW TO VALIDATE PARAMETERS IN STORED PROCEDURE.

SELECT * FROM SALESLT.PRODUCT;

IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'VALIDPROC' AND TYPE = 'P')
DROP PROCEDURE VALIDPROC
GO
CREATE PROCEDURE VALIDPROC(@COLOR VARCHAR(20))
AS 
BEGIN
    -- CHECKING IF MULTIPLE VALUES PASS BY USER
         IF CHARINDEX(',',@COLOR) > 0
		 BEGIN
		    PRINT 'MULTIPLE VALUES CAN NOT BE PASSED';
			RETURN
		 END
		
		 IF NOT EXISTS(SELECT 1 FROM SALESLT.PRODUCT WHERE COLOR = @COLOR)
		 BEGIN
		    PRINT ' ERROR!! VALUE DOESNOT EXIST IN A TABLE';
			RETURN
		 END

END

SELECT COLOR,COUNT(*) FROM SALESLT.PRODUCT GROUP BY COLOR HAVING COLOR = @COLOR;
END





















