-- ============================== CONDITIONAL CONTROL STATEMENT ==============================

-- CASE STATEMENT

SELECT * FROM HUMANRESOURCES.EMPLOYEE;

SELECT * INTO EMPLOYEEDATA FROM HUMANRESOURCES.EMPLOYEE;

SELECT * FROM EMPLOYEEDATA;

UPDATE EMPLOYEEDATA SET MARITALSTATUS = 'U' WHERE BUSINESSENTITYID IN (1,2,6,8,9,22,33,56,76,121);

SELECT CASE WHEN MARITALSTATUS = 'M' THEN 'MARRIED'
            WHEN MARITALSTATUS = 'S' THEN 'SINGLE' 
			ELSE 'UNMARRIED' END AS NEWMARITALSTATUS,
			MARITALSTATUS, * 
FROM EMPLOYEEDATA;

-- IF STATEMENT.

SELECT * FROM EMPLOYEES;

DECLARE @SALARY1 MONEY, @SALARY2 MONEY

SELECT @SALARY1 = SALARY FROM EMPLOYEES WHERE EMP_ID = 203;
SELECT @SALARY2 = SALARY FROM EMPLOYEES WHERE EMP_ID = 207;

IF @SALARY1 = @SALARY2
 BEGIN
   PRINT 'SALARIES ARE EQUAL';
 END
ELSE
 BEGIN
   PRINT 'SALARIES ARE NOT EQUAL';
 END
  