-- ========================= OUTPUT PARAMETERS IN STORED PROCEDURE ====================================

SELECT * FROM SYS.OBJECTS WHERE TYPE = 'P';

SELECT * FROM EMPLOYEES;

CREATE PROC EMP_PROC1(@EID INT, @ENAME VARCHAR(50) OUT)
AS
BEGIN
SELECT @ENAME = NAME FROM EMPLOYEES WHERE EMP_ID = @EID;
END

-- EXECUTION 

DECLARE @ENAME VARCHAR(50) 
EXEC EMP_PROC1 203, @ENAME OUTPUT
SELECT @ENAME;

CREATE PROCEDURE EMP_PROC2(@EID INT, @ENAME VARCHAR(50) OUT, @EAGE INT OUT)
AS
BEGIN
SELECT @ENAME = NAME, @EAGE = AGE FROM EMPLOYEES WHERE EMP_ID = @EID;
END

--EXECUTION

DECLARE @ENAME VARCHAR(50), @EAGE INT
EXEC EMP_PROC2 201, @ENAME OUTPUT, @EAGE OUTPUT
SELECT @ENAME,@EAGE;

-- ======== HOW TO INSERT DATA INTO TABLE BY USING STORED PROCEDURE. ===============

SELECT * FROM AMAN;

SELECT *,ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ID) AS RNUM FROM AMAN;

SELECT *,ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ID) AS RNUM INTO AMAN_DUP FROM AMAN;

SELECT * FROM AMAN_DUP;

DELETE FROM AMAN_DUP WHERE RNUM = 2;

ALTER TABLE AMAN_DUP DROP COLUMN RNUM;

INSERT INTO AMAN_DUP VALUES(30,'SONU','NOIDA',31);
INSERT INTO AMAN_DUP VALUES(40,'MONU','DELHI',30);
INSERT INTO AMAN_DUP VALUES(50,'NISHA','GURUGRAM',24);

CREATE CLUSTERED INDEX PK_INDEX ON AMAN_DUP(ID);

CREATE PROCEDURE AMAN_PROC1(@EID INT, @ENAMES VARCHAR(50), @ECITY VARCHAR(50),@EAGE INT)
AS
BEGIN
INSERT INTO AMAN_DUP(ID,NAMES,CITY,AGE) VALUES(@EID,@ENAMES,@ECITY,@EAGE);
END

EXEC AMAN_PROC1 70,'GAGAN','DAMAN',35;


