-- CONVERSION FUNCTION

-- CAST()

SELECT * FROM SALESLT.PRODUCT;

SELECT PRODUCTID + ' ' + COLOR, * FROM SALESLT.PRODUCT;  -- IT WILL RETURN CONVERSION ERROR.

SELECT CAST(PRODUCTID AS VARCHAR(50)) + ' ' + COLOR,* FROM SALESLT.PRODUCT; 

SELECT 'MY NAME IS' + NAME + ' ' + 'AND MY COLOR IS' + COLOR + ' ' +
'AND MY PRODUCT MODEL ID IS' + PRODUCTMODELID,    -- CONVERSION ERROR
* FROM SALESLT.PRODUCT;

SELECT 'MY NAME IS ' + NAME + ' ' + 'AND MY COLOR IS ' + COLOR + ' ' +
'AND MY PRODUCT MODEL ID IS ' + CAST(PRODUCTMODELID AS VARCHAR(100)),
* FROM SALESLT.PRODUCT;

SELECT CAST(WEIGHT AS INT),* FROM SALESLT.PRODUCT;

--CONVERT()

SELECT CONVERT(INT,STANDARDCOST) AS STANDARDCOST,* FROM SALESLT.PRODUCT;

SELECT CONVERT(VARCHAR(50), PRODUCTID) + ' ' + COLOR,* FROM SALESLT.PRODUCT; 

-- MAJORLY CONVERT() IS USED TO CHANGE THE FORMAT OF DATETIME DATATYPE.

SELECT CONVERT(VARCHAR,SELLSTARTDATE,0),* FROM SALESLT.PRODUCT;

SELECT CONVERT(VARCHAR,SELLSTARTDATE,10),* FROM SALESLT.PRODUCT;

-- DATETIME CONVERSION FORMAT EXAMPLE.

SELECT CONVERT(VARCHAR,GETDATE());
SELECT CONVERT(VARCHAR,GETDATE(),0);
SELECT CONVERT(VARCHAR,GETDATE(),1);
SELECT CONVERT(VARCHAR,GETDATE(),2);
SELECT CONVERT(VARCHAR,GETDATE(),3);
SELECT CONVERT(VARCHAR,GETDATE(),4);
SELECT CONVERT(VARCHAR,GETDATE(),5);
SELECT CONVERT(VARCHAR,GETDATE(),6);
SELECT CONVERT(VARCHAR,GETDATE(),7);
SELECT CONVERT(VARCHAR,GETDATE(),8);
SELECT CONVERT(VARCHAR,GETDATE(),9);
SELECT CONVERT(VARCHAR,GETDATE(),10);
SELECT CONVERT(VARCHAR,GETDATE(),11);
SELECT CONVERT(VARCHAR,GETDATE(),12);
SELECT CONVERT(VARCHAR,GETDATE(),13);
SELECT CONVERT(VARCHAR,GETDATE(),14);
--SELECT CONVERT(VARCHAR,GETDATE(),15);
SELECT CONVERT(VARCHAR,GETDATE(),16);
SELECT CONVERT(VARCHAR,GETDATE(),17);
SELECT CONVERT(VARCHAR,GETDATE(),18);
SELECT CONVERT(VARCHAR,GETDATE(),19);
SELECT CONVERT(VARCHAR,GETDATE(),20);
SELECT CONVERT(VARCHAR,GETDATE(),21);
SELECT CONVERT(VARCHAR,GETDATE(),22);
SELECT CONVERT(VARCHAR,GETDATE(),23);
SELECT CONVERT(VARCHAR,GETDATE(),24);
SELECT CONVERT(VARCHAR,GETDATE(),25);

SELECT CONVERT(VARCHAR,GETDATE(),100);
SELECT CONVERT(VARCHAR,GETDATE(),101);
SELECT CONVERT(VARCHAR,GETDATE(),102);
SELECT CONVERT(VARCHAR,GETDATE(),103);
SELECT CONVERT(VARCHAR,GETDATE(),104);
SELECT CONVERT(VARCHAR,GETDATE(),105);
SELECT CONVERT(VARCHAR,GETDATE(),106);
SELECT CONVERT(VARCHAR,GETDATE(),107);
SELECT CONVERT(VARCHAR,GETDATE(),108);
SELECT CONVERT(VARCHAR,GETDATE(),109);
SELECT CONVERT(VARCHAR,GETDATE(),110);
SELECT CONVERT(VARCHAR,GETDATE(),111);
SELECT CONVERT(VARCHAR,GETDATE(),112);
SELECT CONVERT(VARCHAR,GETDATE(),113);
SELECT CONVERT(VARCHAR,GETDATE(),121);





